 { name: "Dr. Sneha Desai", specialization: "General Medicine", location: "Dadar, Mumbai", availableSlots: ["11:00 AM", "3:00 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Rajiv Agarwal", specialization: "Cardiology", location: "Bandra, Mumbai", availableSlots: ["9:00 AM", "1:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Anita Sharma", specialization: "Cardiology", location: "Mulund, Mumbai", availableSlots: ["10:30 AM", "2:30 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Meena Patil", specialization: "Pediatrics", location: "Powai, Mumbai", availableSlots: ["9:00 AM", "12:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Prashant Kothari", specialization: "Pediatrics", location: "Juhu, Mumbai", availableSlots: ["10:00 AM", "2:00 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Vikas Deshmukh", specialization: "Orthopedics", location: "Borivali, Mumbai", availableSlots: ["8:00 AM", "11:00 AM", "3:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Alka Sharma", specialization: "Orthopedics", location: "Malad, Mumbai", availableSlots: ["10:00 AM", "1:00 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Shweta Mehra", specialization: "Dermatology", location: "Colaba, Mumbai", availableSlots: ["9:00 AM", "2:00 PM", "5:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Ajay Khanna", specialization: "Dermatology", location: "Vile Parle, Mumbai", availableSlots: ["11:00 AM", "3:00 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Anil Pandey", specialization: "Neurology", location: "Navi Mumbai", availableSlots: ["9:00 AM", "12:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Rekha Rathi", specialization: "Neurology", location: "Khar, Mumbai", availableSlots: ["10:00 AM", "2:00 PM"], consultations: ["In-clinic"] },

        // Bangalore
        { name: "Dr. Pooja Narayan", specialization: "General Medicine", location: "Koramangala, Bangalore", availableSlots: ["10:00 AM", "2:00 PM", "5:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Rajesh Gupta", specialization: "General Medicine", location: "Whitefield, Bangalore", availableSlots: ["11:00 AM", "3:00 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Arvind Kumar", specialization: "Cardiology", location: "Indiranagar, Bangalore", availableSlots: ["9:00 AM", "1:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Smita Reddy", specialization: "Cardiology", location: "Malleshwaram, Bangalore", availableSlots: ["10:30 AM", "2:30 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Vinay Kothari", specialization: "Orthopedics", location: "Jayanagar, Bangalore", availableSlots: ["8:00 AM", "11:00 AM", "3:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Sudhir Naik", specialization: "Cardiology", location: "Jayanagar, Bangalore", availableSlots: ["11:00 AM", "2:30 PM", "4:30 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Vinay Kothari", specialization: "Orthopedics", location: "Jayanagar, Bangalore", availableSlots: ["10:00 AM", "12:30 PM", "3:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Anil Deshpande", specialization: "Orthopedics", location: "Koramangala, Bangalore", availableSlots: ["9:00 AM", "1:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Manju Desai", specialization: "Orthopedics", location: "Whitefield, Bangalore", availableSlots: ["10:30 AM", "1:30 PM", "3:30 PM"], consultations: ["In-clinic", "Video Consultation"] },

        // Hyderabad
        { name: "Dr. Neeta Kapoor", specialization: "Pediatrics", location: "Banjara Hills, Hyderabad", availableSlots: ["9:00 AM", "12:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Vivek Reddy", specialization: "Pediatrics", location: "Gachibowli, Hyderabad", availableSlots: ["10:00 AM", "2:00 PM", "5:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Aruna Reddy", specialization: "Pediatrics", location: "Kondapur, Hyderabad", availableSlots: ["9:30 AM", "12:30 PM", "3:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Preeti Shetty", specialization: "Dermatology", location: "Jubilee Hills, Hyderabad", availableSlots: ["9:00 AM", "1:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Mohan Rao", specialization: "Dermatology", location: "Kukatpally, Hyderabad", availableSlots: ["10:00 AM", "2:00 PM", "5:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Shruti Gupta", specialization: "Dermatology", location: "Banjara Hills, Hyderabad", availableSlots: ["9:30 AM", "12:00 PM", "4:30 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Ajay Pandey", specialization: "Neurology", location: "Begumpet, Hyderabad", availableSlots: ["9:00 AM", "1:00 PM", "3:30 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Ramesh Kumar", specialization: "Neurology", location: "Ameerpet, Hyderabad", availableSlots: ["10:00 AM", "2:30 PM", "5:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Sudhir Reddy", specialization: "Neurology", location: "Kukatpally, Hyderabad", availableSlots: ["9:30 AM", "12:30 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },

        // Delhi
        { name: "Dr. Sanjay Chopra", specialization: "General Medicine", location: "South Delhi, Delhi", availableSlots: ["9:00 AM", "12:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Ritu Gupta", specialization: "General Medicine", location: "Connaught Place, Delhi", availableSlots: ["10:00 AM", "2:00 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Anil Mehta", specialization: "Cardiology", location: "Rajouri Garden, Delhi", availableSlots: ["9:00 AM", "1:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Sonia Verma", specialization: "Cardiology", location: "Lajpat Nagar, Delhi", availableSlots: ["10:30 AM", "2:30 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Rakesh Kumar", specialization: "Orthopedics", location: "Dwarka, Delhi", availableSlots: ["8:00 AM", "11:00 AM", "3:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Vikram Singh", specialization: "General Medicine", location: "Connaught Place, Delhi", availableSlots: ["10:00 AM", "2:00 PM", "5:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Priya Arora", specialization: "Pediatrics", location: "Karol Bagh, Delhi", availableSlots: ["9:00 AM", "12:00 PM", "4:00 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Ravi Kumar", specialization: "Cardiology", location: "Saket, Delhi", availableSlots: ["11:00 AM", "3:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Nisha Gupta", specialization: "Orthopedics", location: "Lajpat Nagar, Delhi", availableSlots: ["8:00 AM", "12:00 PM", "3:00 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Aditi Mehra", specialization: "Dermatology", location: "Vasant Kunj, Delhi", availableSlots: ["9:30 AM", "1:30 PM", "4:30 PM"], consultations: ["In-clinic", "Video Consultation"] },

        // Chennai
        { name: "Dr. Radhika Nair", specialization: "General Medicine", location: "Anna Nagar, Chennai", availableSlots: ["10:00 AM", "2:00 PM", "5:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Mohan Srinivasan", specialization: "General Medicine", location: "T Nagar, Chennai", availableSlots: ["11:00 AM", "3:00 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Prakash Subramaniam", specialization: "Cardiology", location: "Mylapore, Chennai", availableSlots: ["9:00 AM", "1:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Anjali Iyer", specialization: "Cardiology", location: "Adyar, Chennai", availableSlots: ["10:30 AM", "2:30 PM"], consultations: ["In-clinic"] },
        { name: "Dr. Aruna Reddy", specialization: "Pediatrics", location: "Velachery, Chennai", availableSlots: ["9:00 AM", "12:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Sathish Kumar", specialization: "General Medicine", location: "T Nagar, Chennai", availableSlots: ["10:00 AM", "1:00 PM", "4:00 PM"], consultations: ["In-clinic", "Video Consultation"] },
        { name: "Dr. Anjali Nair", specialization: "Pediatrics", location: "Mylapore, Chennai", availableSlots: ["8:30 AM", "12:00 PM", "3:30 PM"], consultations: ["In-clinic"] },